#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received. Deploying master branch to production..."
        git --work-tree=/var/www/dehaagsemunt/api --git-dir=/var/git/dehaagsemunt/api/.git checkout -f
      	cd /var/www/dehaagsemunt/api
        ls -la
      	cp /home/admin/config/dehaagsemunt/api/pm2.json ./pm2.json
      	npm install
      	pm2 start pm2.json
      	echo "done."

    else
        echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
